# Generated by Django 3.1.7 on 2021-03-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='credential_id',
            field=models.BinaryField(max_length=250),
        ),
        migrations.AlterField(
            model_name='webauthncredential',
            name='public_key',
            field=models.BinaryField(max_length=500),
        ),
    ]
