# Generated by Django 3.1.7 on 2021-03-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0003_auto_20210329_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthncredential',
            name='raw_id',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
