# Generated by Django 3.1.7 on 2021-03-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0005_fill_raw_id_from_credential_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='raw_id',
            field=models.CharField(unique=True, max_length=300),
        ),
    ]
