# Generated by Django 3.1.7 on 2021-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0006_unique_raw_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthncredential',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
