# Generated by Django 3.1.7 on 2021-04-04 09:29

from django.db import migrations


def fill_name_from_id(apps, schema_editor):
    WebAuthnCredential = apps.get_model("webauth", "WebAuthnCredential")
    for row in WebAuthnCredential.objects.all():
        row.name = row.credential_id
        row.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0007_webauthncredential_name'),
    ]

    operations = [
        migrations.RunPython(fill_name_from_id, reverse_code=migrations.RunPython.noop),
    ]
