# Generated by Django 3.1.7 on 2021-04-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webauth', '0008_populate_webauthncredential_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webauthncredential',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
